name: Prettier Auto-Fix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Prettier
        run: npm install --global prettier

      - name: Run Prettier (auto-fix Markdown)
        run: prettier --write "**/*.md"

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add "**/*.md"
          git diff --cached --quiet || git commit -m "Auto-fix Markdown with Prettier"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
