name: Daily Automated Update

on:
  schedule:
    - cron: '0 13 * * *' # Runs daily at 9AM Eastern (adjust as needed)
  workflow_dispatch:

jobs:
  new_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create new update post
        run: |
          mkdir -p automation-tips
          echo "# Automation Tip Of The Day

Use the proposal template in this repo to save time on client quotes.
A reusable template helps maintain accuracy and a professional appearance.

Support the project and receive daily tips customized for your workflow.
" > automation-tips/${{ env.DATE }}-automation-tip.md

      - name: Commit post
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add automation-tips/
          git commit -m "Add automated update for ${{ env.DATE }}" || echo "Nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
