name: Daily Automation Tip

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  new_tip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up date variable
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Rotate and create automation tip
        run: |
          mkdir -p automation-tips
          TOTAL=$(grep -c '^# Automation Tip Of The Day' automation-tips.txt)
          IDX=$(( ($(date +%j) - 1) % TOTAL + 1 ))
          awk -v idx="$IDX" 'BEGIN{RS="---"} NR==idx{print $0 > "automation-tips/" ENVIRON["DATE"] "-automation-tip.md"}' automation-tips.txt

      - name: Commit post
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add automation-tips/
          git commit -m "Add automation tip for $DATE" || echo "No changes to commit."
          git push
        env:
          DATE: ${{ env.DATE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
