name: Daily Automated Update

on:
  schedule:
    - cron: '0 7 * * *' # Runs every day at 7:00 UTC
  workflow_dispatch:    # Allows manual trigger from GitHub UI

jobs:
  new_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up date variable
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create new update post
        run: |
          mkdir -p updates
          echo "# Daily Automated Update - $DATE" > updates/${DATE}-daily-update.md
          echo "" >> updates/${DATE}-daily-update.md
          echo "This is your automated update for $DATE." >> updates/${DATE}-daily-update.md

      - name: Commit post
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add updates/
          git commit -m "Add automated update for $DATE" || echo "No changes to commit."
          git push
        env:
          DATE: ${{ env.DATE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
